# Generated by Django 3.1 on 2020-10-20 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0003_auto_20201020_0548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='profile',
        ),
    ]
